#In this block background of our streamlit platform receives a dark color
[theme]
base="dark"
primaryColor="#1f77b4"
backgroundColor="#000000"
secondaryBackgroundColor="#111111"
textColor="#ffffff"
font="sans serif"
