#In this block background of our streamlit platform receives a dark color
[theme]
base="dark"
primaryColor="#E50914"
backgroundColor="#000000"
secondaryBackgroundColor="#1a1a1a"
textColor="#ffffff"
font="sans serif"
